#include "config.h"

#include "../memory/memory.h"

#include <stdio.h>
#include <string.h>

static ae_ParseConfig_Error ae_parse_config(toml_table_t* table, ae_Config* out_config) {
  toml_table_t* game = toml_table_in(table, "game");
  if (!game) {
    return AE_PARSECONFIGERROR_INVALID_GAME_SECTION;
  }

  toml_datum_t game_target = game_target = toml_string_in(game, "target");
  if (!game_target.ok) {
    return AE_PARSECONFIGERROR_INVALID_GAME_SECTION;
  }
  out_config->game_target = game_target.u.s;
  
  return AE_PARSECONFIGERROR_SUCCESS;
}

bool ae_locate_config_file(cstr* out_location) {
  tinydir_dir current_directory;
  if (tinydir_open(&current_directory, ".") != 0) {
    return false;
  }
  
  bool result = ae_locate_config_file_in_dir(&current_directory, out_location);

  tinydir_close(&current_directory);

  return result;
}

bool ae_locate_config_file_in_dir(tinydir_dir* search_dir, cstr* out_location) {
  while(search_dir->has_next) {
    tinydir_file file;
    tinydir_readfile(search_dir, &file);

    if (
      !file.is_dir &&
      strcmp(file.name, AE_CONFIG_DEFAULT_NAME) == 0
    ) {
      *out_location = cstr_from(file.path);
      return true;
    }

    tinydir_next(search_dir);
  }

  return false;
}

ae_ParseConfig_Error ae_config_init_from_file(csview file_name, ae_Config* out_config) {
  FILE* file = fopen(file_name.buf, "r");
  toml_table_t* table = toml_parse_file(file, NULL, 0);
  if (!table) {
    toml_free(table);
    fclose(file);
    return AE_PARSECONFIGERROR_COULD_NOT_PARSE;
  }

  out_config->source = (ae_ConfigSource){
    .type = AE_CONFIGSOURCETYPE_FROM_FILE,
    .value.file = file_name.buf, 
  };
  
  ae_ParseConfig_Error result = ae_parse_config(table, out_config);

  fclose(file);
  toml_free(table);
  
  return result;
}

ae_ParseConfig_Error ae_config_init_from_toml(toml_table_t* table, ae_Config* out_config) {
  out_config->source = (ae_ConfigSource){
    .type = AE_CONFIGSOURCETYPE_FROM_SOURCE,
    .value.none = 0,
  };
  
  return ae_parse_config(table, out_config);
}

void ae_config_init_from_default(ae_Config* out_config) {
  out_config->source = (ae_ConfigSource){
    .type = AE_CONFIGSOURCETYPE_AUTOGENERATED,
    .value.none = 0,
  };
  out_config->game_target = AE_CONFIG_DEFAULT_GAMETARGET;
}

void ae_config_free(ae_Config* config) {
  ae_free((void*)(config->game_target));
  config->game_target = 0;
}
