#pragma once

#include <amber_engine/common/types.h>

static const char* AE_CONFIG_DEFAULT_NAME = "config.toml";
static const char* AE_CONFIG_DEFAULT_GAMETARGET = "game";

typedef enum {
	AE_CONFIGSOURCETYPE_AUTOGENERATED,
	AE_CONFIGSOURCETYPE_FROM_SOURCE,
	AE_CONFIGSOURCETYPE_FROM_FILE,
} ae_ConfigSourceType;

typedef ae_tagged_union {
	ae_ConfigSourceType type;
	union {
		const char* file;
		ae_none none;
	} value;
} ae_ConfigSource;

typedef struct {
	ae_ConfigSource source;

	const char* game_target;
} ae_Config;
